In [ ]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle as pickle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Loading the dataset from the CSV file named 'Social_Network_Ads.csv'
dataset=pd.read_csv("Social_Network_Ads.csv")

In [ ]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
# Perform one-hot encoding on categorical variables and drop the first category to avoid the dummy variable trap (multicollinearity)
dataset=pd.get_dummies(dataset,drop_first=True)

In [ ]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [ ]:
# Drop the 'User ID' column as it is just an identifier and not useful for prediction
dataset = dataset.drop("User ID", axis=1)

In [ ]:
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0         True
1     35            20000          0         True
2     26            43000          0        False
3     27            57000          0        False
4     19            76000          0         True
..   ...              ...        ...          ...
395   46            41000          1        False
396   51            23000          1         True
397   50            20000          1        False
398   36            33000          0         True
399   49            36000          1        False

[400 rows x 4 columns]

In [ ]:
# Display the count of each class in the target variable 'Purchased' (0 = Not Purchased, 1 = Purchased)
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [ ]:
# Define independent variables/features for the model
indep = dataset[["Age", "EstimatedSalary", "Gender_Male"]]

# Define dependent variable/target for prediction
dep = dataset["Purchased"]

In [ ]:
# Check the shape (rows, columns) of the independent variables dataframe
indep.shape

(400, 3)

In [ ]:
# Display the target variable 'Purchased' values
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
# Split data into training and test sets
# test_size=1/3 means 33% data for testing, 67% for training
# random_state=0 ensures reproducibility of the split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size=1/3, random_state=0)

In [ ]:
# Create a Random Forest classifier with 10 trees using entropy as the splitting criterion
classifier = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)

# Train the classifier on the training data
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [ ]:
# Predict the target values for the test set using the trained Random Forest classifier
y_pred = classifier.predict(X_test)

In [ ]:
# Compute the confusion matrix to evaluate the accuracy of the classification
cm = confusion_matrix(y_test, y_pred)

In [ ]:
print(cm)

[[78  7]
 [ 5 44]]


In [ ]:
# Generate a detailed classification report including precision, recall, f1-score, and support
clf_report = classification_report(y_test, y_pred)

In [ ]:
print(clf_report)
# Precision: Proportion of positive predictions that are actually correct (true positives out of all predicted positives).
# Recall: Proportion of actual positive cases that the model successfully identified (true positives out of all actual positives).
# F1-score: The harmonic mean of precision and recall, providing a balanced measure that accounts for both false positives and false negatives.

              precision    recall  f1-score   support

           0       0.94      0.92      0.93        85
           1       0.86      0.90      0.88        49

    accuracy                           0.91       134
   macro avg       0.90      0.91      0.90       134
weighted avg       0.91      0.91      0.91       134



In [ ]:
# Print the confusion matrix showing:
# [[TN, FP],
#  [FN, TP]]
# TN = True Negatives: correctly predicted negatives (class 0)
# FP = False Positives: incorrectly predicted positives (predicted 1 but actual 0)
# FN = False Negatives: incorrectly predicted negatives (predicted 0 but actual 1)
# TP = True Positives: correctly predicted positives (class 1)
print(cm)

[[78  7]
 [ 5 44]]


In [ ]:
age_input=float(input("Age:"))
salary_input=float(input("Salary:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age: 60
Salary: 20000
Sex Male 0 or 1: 1


In [ ]:
# Predict the class (Purchased or Not) for a new user with input features: age, estimated salary, and gender (male encoded as 0/1)
classifier.predict([[age_input, salary_input, sex_male_input]])

C:\Users\mukil\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [ ]:
# List all the attributes and methods of the classification report object (usually a string)
dir(clf_report)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [ ]:
# 📁 Save the trained model
filename = "finalized_model_rf.sav"
pickle.dump(classifier, open(filename, 'wb'))  # 'wb' = write binary

In [ ]:
# 🔁 Load the saved model
loaded_model = pickle.load(open("finalized_model_rf.sav", 'rb'))  # 'rb' = read binary

In [ ]:
# 🔮 Make a prediction
# Example: Predict on a new user with Age=35, EstimatedSalary=75000
loaded_model.predict([[60, 150000,0]])

C:\Users\mukil\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [ ]:
print("Prediction:", result[0])  # Output: 0 or 1 (Not Purchased or Purchased)
print("Prediction for [60, 150000]:", loaded_model.predict([[60, 150000,0]])[0])  # Likely to return 1
print("Prediction for [35, 75000]:", loaded_model.predict([[35, 75000,0]])[0])


Prediction: 0
Prediction for [60, 150000]: 1
Prediction for [35, 75000]: 0


C:\Users\mukil\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
C:\Users\mukil\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
